import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavbarDemo from "@/components/resizable-navbar-demo";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mock Up",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${outfit.variable} h-full antialiased`}>
        <body className="min-h-full flex flex-col font-outfit">
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
